import axios from "axios";
import { defineStore } from "pinia";

// Generated by https://quicktype.io

export interface Complaint {
  id: number;
  category: string;
  createdDate: string;
  closeDate: null;
  status: number;
  title: string;
  description: string;
  address: string;
  latitude: null;
  image: string;
  longitude: null;
  userId: string;
  messages: Message[];
  logs: Log[];
}

export interface Log {
  id: number;
  complaintId: number;
  logText: string;
  logDate: string;
}

export interface Message {
  id: number;
  complaintId: number;
  userId: string;
  message: string;
  messageDate: string;
}

const token = localStorage.getItem("id_token");

export const useComplaintsStore = defineStore("allComplaints", {
  state: () => ({
    complaints: [] as Complaint[],
  }),
  actions: {
    async fetchComplaints() {
      try {
        const response = await axios.get<Complaint[]>(
          `${import.meta.env.VITE_APP_COMPLAINTS_API}`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );
        this.complaints = response.data;
      } catch (error) {
        console.error("Error fetching complaints:", error);
      }
    },
  },
});
